import Home from "./Home";
import Cart from "./Cart";
import Shop from "./Shop";
import Product from "./Product";
import Login from "./Login";
import About from "./About";
import Contact from "./Contact";
import Checkout from "./Checkout";
import Orders from "./Orders";
import Emailverification from "./Emailverification";
export { Home, Cart, Shop, Product, Login, About, Contact, Checkout, Orders, Emailverification };